[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd api",
  "python -m pip install --upgrade pip",
  "python -m pip install -e ."
]

[start]
cmd = "cd api && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
