[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd api && python -m pip install --upgrade pip && python -m pip install -e ."
]

[phases.build]
cmds = [
  "ls -la data || echo 'Warning: data directory not found in root'",
  "cp -r data api/data && echo 'Successfully copied data to api/data' || echo 'ERROR: Failed to copy data directory'",
  "ls -la api/data || echo 'ERROR: api/data directory does not exist after copy'"
]

[start]
cmd = "cd api && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
