version: '3.8'

services:
  rh-ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map container port 3000 to host port 3001
    environment:
      - NEXT_PUBLIC_APP_NAME=RH AI Assistant
      - NODE_ENV=development
      - MOCK_MODE=true
      - GEN_BACKEND=OPENAI
      - DATABASE_URL=file:./dev.db
      - PASSWORD_GATE_ENABLED=false
      - PASSWORD_GATE_VALUE=changeme
    volumes:
      - ./data:/app/data:ro  # Mount data directory as read-only
      - db-data:/app  # Persist database
    restart: unless-stopped

volumes:
  db-data:
